kind: Service
apiVersion: v1
metadata:
  name: branches-backend-service
  labels:
    app: branches-backend
spec:
  type: ClusterIP
  selector:
    app: branches-backend
  ports:
    - port: 80
      targetPort: 8080
      name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: branches-backend-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: "csas.micro.ivandelic.com"
      http:
        paths:
          - path: /branch-manager(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: branches-backend-service
                port:
                  number: 80
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: branches-backend-deployment
  labels:
    app: branches-backend
spec:
  selector:
    matchLabels:
      app: branches-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: branches-backend
        version: v1
    spec:
      containers:
        - name: branches-backend
          image: 'fra.ocir.io/frsxwtjslf35/csas/branches-backend:latest'
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ORACLEDB_HOST
                valueFrom:
                  secretKeyRef:
                    name: oracle-db
                    key: host
            - name: ORACLEDB_PORT
              valueFrom:
                secretKeyRef:
                  name: oracle-db
                  key: port
            - name: ORACLEDB_NAME
              valueFrom:
                secretKeyRef:
                  name: oracle-db
                  key: name
            - name: ORACLEDB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: oracle-db
                  key: username
            - name: ORACLEDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oracle-db
                  key: password
      imagePullSecrets:
        - name: ocirsecret