kind: Service
apiVersion: v1
metadata:
  name: departments-frontend-service
  labels:
    app: departments-frontend
spec:
  type: ClusterIP
  selector:
    app: departments-frontend
  ports:
    -
      port: 80
      targetPort: 3000
      name: http
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: frontend-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: "csas.micro.ivandelic.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: departments-frontend-service
            port:
              number: 3000
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: departments-frontend-deployment
  labels:
    app: departments-frontend
spec:
  selector:
    matchLabels:
      app: departments-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: departments-frontend
        version: v1
    spec:
      containers:
        -
          name: departments-frontend
          image: 'fra.ocir.io/frsxwtjslf35/csas/departments-frontend:latest'
          imagePullPolicy: Always
          ports:
            -
              containerPort: 3000
          env:
            - name: REACT_APP_API_URL
              value: http://csas-api.micro.ivandelic.com/department-manager
      imagePullSecrets:
        -
          name: ocirsecret